1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [2]:
import numpy as np

In [ ]:
#1
ar1 = np.arange(30) 
ar1.reshape(15,2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [ ]:
#2
ar2 = np.random.randint(0,100,60)
ar2.reshape(2,5,-1)

array([[[49, 71, 59, 25, 44, 51],
        [28, 27, 81, 57, 86, 41],
        [35, 50,  9, 43, 66, 88],
        [91, 56, 95, 53, 46, 35],
        [98, 14, 41, 89, 21, 34]],

       [[11,  5, 21, 14, 34, 84],
        [39, 57, 54, 41, 83, 74],
        [91, 97, 98, 99,  3, 37],
        [ 9, 43, 88, 63, 35, 27],
        [45, 75, 92, 15, 43, 65]]])

In [ ]:
ar2.ndim

1

In [ ]:
#3
ar3 =np.array([[1,2,3],[4,5,6],[7,8,9]])
ar3.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#4
ar4 = np.arange(20).reshape(5,4)
for i in ar4:
  for x in i:
    print(x)

for z in np.nditer(ar4):
  print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
#5
ar5 = np.array([5,10,15,20,25])
ar55 = np.array([1,2,3,4,5])
ar5top = ar5 + ar55
ar5c = ar5 - ar55
ar5cap = ar5 * ar55
ar5b = ar5 / ar55
print(ar5top)
print(ar5c)
print(ar5cap)
print(ar5b)

[ 6 12 18 24 30]
[ 4  8 12 16 20]
[  5  20  45  80 125]
[5. 5. 5. 5. 5.]


In [ ]:
#6
ar6 = np.random.randint(0,100,10)
print(ar6)
print(ar6.sum())
print(ar6.mean())
print(ar6.std())

[77 40 60 41  7 11 68 92 81 83]
560
56.0
28.56221279943135


In [ ]:
#7
ar7 = np.arange(21)
ar77 = np.arange(500,531)
np.concatenate([ar7,ar77] , axis = 0 )

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [ ]:
#8 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın
ar8 = np.arange(15,51)
ar88 = np.arange(10,101)
ar8con = np.concatenate([ar8,ar88], axis = 0)
ar8con[25:51] = 888
print(ar8con)

[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39 888 888 888 888 888 888 888 888 888 888 888
 888 888 888 888 888 888 888 888 888 888 888 888 888 888 888  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [ ]:
#9 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve 320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın
ar9 = np.arange(0,40).reshape(8,5)
ar99 = np.arange(320,360).reshape(8,5)
ar9con = np.concatenate([ar9,ar99], axis = 0)
print(ar9con)
ar9con1 = np.concatenate([ar9,ar99], axis = 1)
print(ar9con1)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


In [7]:
#10 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın
ar10 = np.arange(0,40).reshape(8,5)
ar100 = np.arange(320,360).reshape(8,5)
ar10con = np.concatenate([ar10,ar100], axis = 1)
print(ar10con)

arstac= np.stack([ar10,ar100] , axis = 1)
print(arstac)


[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]
[[[  0   1   2   3   4]
  [320 321 322 323 324]]

 [[  5   6   7   8   9]
  [325 326 327 328 329]]

 [[ 10  11  12  13  14]
  [330 331 332 333 334]]

 [[ 15  16  17  18  19]
  [335 336 337 338 339]]

 [[ 20  21  22  23  24]
  [340 341 342 343 344]]

 [[ 25  26  27  28  29]
  [345 346 347 348 349]]

 [[ 30  31  32  33  34]
  [350 351 352 353 354]]

 [[ 35  36  37  38  39]
  [355 356 357 358 359]]]


In [8]:
#11 [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

ar11 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(ar11 == 5)


(array([ 5, 13]),)

In [10]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
ar12 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(ar12 % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [11]:
#13)Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
ar13 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(ar13 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [13]:
#14)Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
ar14 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(ar14 % 5 == 0)

(array([ 1,  2,  5, 13]),)

In [15]:
#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
np.random.randint(85,101)

88

In [17]:
#16 İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun. 
np.random.randint(10,99,9).reshape(3,3)

array([[12, 51, 52],
       [27, 77, 57],
       [61, 82, 50]])

In [19]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
ar17 = np.random.randint(35,60,10)
print(ar17)
np.random.choice(ar17)

[50 45 54 44 49 49 43 44 35 49]


54

In [22]:
#18 sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
np.array([3, 8, 10, 53,0,0,0,0,0,0]).reshape(2,5)

array([[ 3,  8, 10, 53,  0],
       [ 0,  0,  0,  0,  0]])